---
title: "Advanced Bioinformatics 2019 Assessment"
author: "Melissa Kow 9534"
date: "05/06/2019"
output: html_document
keep_md: yes

---

# TASK 1
```{r}
sum(5:55)
```

# TASK 2
```{r}
sumfun<- function (n) 
sum(5:n)
```

sumfun(10)
```{r}
sum(5:10)
```
sumfun(20)
```{r}
sum(5:20)
```
sumfun(100)
```{r}
sum(5:100)
```
# TASK 3
```{r}
Fibonacci_seq <- numeric(12)
Fibonacci_seq[1] <- 1
Fibonacci_seq[2] <- 1
for (i in 3:12) { 
   Fibonacci_seq[i] <- Fibonacci_seq[i-1]+Fibonacci_seq[i-2]
}
print("The first 12 numbers of the Fibonacci sequence are:")
print(Fibonacci_seq)
```
# TASK 4
```{r}
library(ggplot2)
ggplot(data=mtcars,aes(x=as.factor(gear),y=mpg,fill=gear)) + geom_boxplot()
```

# TASK 5

```{r}
cars.lm <- lm(dist ~ speed, data = cars)
summary(cars.lm)
```
Intercept: -17.5791 
Fitted Slope: 3.9324
Standard Deviation: 0.4155

# TASK 6
```{r}
library(grid)
library(gridExtra)
library(gtable)
lm.scatter <- ggplot(cars, aes(x=speed, y=dist)) + 
  geom_point(color='#2980B9', size = 4) + xlim(c(0, 25)) + 
  geom_smooth(method=lm, se=FALSE, fullrange=TRUE, color='#2C3E50') + 
  labs(title='Linear relationship Between Speed and Breaking Distance')
grid.arrange(lm.scatter)
```

# TASK 7

```{r}
new_speed <- cars$speed * (5280/3600)
line<-lm(dist ~ 0+ new_speed + I(new_speed^2),cars)
summary(line)
```
```{r}
ggplot(data, aes(x = new_speed, y = dist)) + 
 geom_point(color='Black', size = 1) + xlim(c(0,40)) +
 geom_smooth(method = "lm", formula = "y ~ 0 + x + I(x^2)",  color="red", fullrange='TRUE') + labs(title= 'Reaction Time for the Driver to Start Breaking', y = 'Stopping Distance (feet)', x = "New Speed")
```

